# Generated by Django 4.2.3 on 2024-08-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spacial', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=64, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spacial', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('national_id', models.CharField(max_length=10, verbose_name='national_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spacial', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='sku')),
                ('part_number', models.CharField(max_length=350, unique=True, verbose_name='part number')),
                ('quality', models.CharField(blank=True, max_length=100, null=True, verbose_name='quality')),
                ('price', models.FloatField(verbose_name='price')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='core.brand', verbose_name='brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spacial', models.BooleanField(default=False)),
                ('request_date', models.DateField(verbose_name='request_date')),
                ('cancel', models.BooleanField(default=False, verbose_name='cancel')),
                ('sale_type', models.PositiveSmallIntegerField(choices=[(1, 'نقدی'), (2, 'یک ماهه'), (3, 'سه ماهه')], verbose_name='sale_type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer', verbose_name='customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spacial', models.BooleanField(default=False)),
                ('quantity', models.BigIntegerField(verbose_name='quantity')),
                ('price', models.FloatField(verbose_name='price')),
                ('discount_per_item', models.FloatField(default=0, verbose_name='discount_per_item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_set', to='core.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotation_item_rel', to='core.quotation', verbose_name='quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spacial', models.BooleanField(default=False)),
                ('weight', models.FloatField(verbose_name='weight')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_weights', to='core.item', verbose_name='sku')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
