# Generated by Django 4.2.3 on 2024-08-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemWeight',
        ),
    ]
